apiVersion: v1
kind: ReplicationController
metadata:
  name: digibank
spec:
  replicas: 3
  selector:
    app: digibank
  template:
    metadata:
      name: digibank
      labels:
        app: digibank
    spec:
      containers:
      - name: digibank
        image: digibank
        ports:
        - containerPort: 80
